//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vetrina.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal labels() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vetrina.App_GlobalResources.labels", typeof(labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Abiti da Cerimonia.
        /// </summary>
        public static string AbitiDaCerimonia {
            get {
                return ResourceManager.GetString("AbitiDaCerimonia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Abiti da sposo personalizzati e su misura.&lt;br /&gt;
        ///I nostri abiti da &lt;span style=&quot;color:gray&quot;&gt;sposo&lt;/span&gt; sono perfetti per il giorno più importante
        ///della tua vita. Puoi disegnare il tuo abito nuziale online optando
        ///per un modello classico o più moderno a seconda delle tue
        ///preferenze. Lo sposo deve vestire con raffinatezza,
        ///distinguendosi da tutti gli invitati sia per il ruolo che ovviamente
        ///per il suo&lt;span style=&quot;color:gray&quot;&gt; outfit&lt;/span&gt;..
        /// </summary>
        public static string AbitoParIndex {
            get {
                return ResourceManager.GetString("AbitoParIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Chi siamo.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Accedi.
        /// </summary>
        public static string Accedi {
            get {
                return ResourceManager.GetString("Accedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Accedi o Registrati.
        /// </summary>
        public static string accedi_o_registrati {
            get {
                return ResourceManager.GetString("accedi_o_registrati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Acquista ora.
        /// </summary>
        public static string Acquista_ora {
            get {
                return ResourceManager.GetString("Acquista_ora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Aggiorna dati.
        /// </summary>
        public static string Aggiorna_dati {
            get {
                return ResourceManager.GetString("Aggiorna_dati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Aggiungi al Carrello.
        /// </summary>
        public static string AggiungiCarrello {
            get {
                return ResourceManager.GetString("AggiungiCarrello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Prodotto aggiunto al carrello!.
        /// </summary>
        public static string Aggiunto {
            get {
                return ResourceManager.GetString("Aggiunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Pagina in allestimento.
        /// </summary>
        public static string Allestimento {
            get {
                return ResourceManager.GetString("Allestimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Inserisci un nome per il ritiro.
        /// </summary>
        public static string Asporto_titolo {
            get {
                return ResourceManager.GetString("Asporto_titolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Azioni.
        /// </summary>
        public static string Azioni {
            get {
                return ResourceManager.GetString("Azioni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Completa l&apos;ordine.
        /// </summary>
        public static string Button_Completa {
            get {
                return ResourceManager.GetString("Button_Completa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Indietro.
        /// </summary>
        public static string Button_Indietro {
            get {
                return ResourceManager.GetString("Button_Indietro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Scopri il menù.
        /// </summary>
        public static string Button_menu {
            get {
                return ResourceManager.GetString("Button_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Modifica l&apos;ordine.
        /// </summary>
        public static string Button_Modifica {
            get {
                return ResourceManager.GetString("Button_Modifica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Effettua un altro ordine.
        /// </summary>
        public static string Button_nuovoOrdine {
            get {
                return ResourceManager.GetString("Button_nuovoOrdine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Procedi con l&apos;ordine.
        /// </summary>
        public static string Button_procedi {
            get {
                return ResourceManager.GetString("Button_procedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Salva.
        /// </summary>
        public static string Button_Salva {
            get {
                return ResourceManager.GetString("Button_Salva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Il Tuo Carrello.
        /// </summary>
        public static string Carrello {
            get {
                return ResourceManager.GetString("Carrello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Vai al carrello.
        /// </summary>
        public static string CarrelloVai {
            get {
                return ResourceManager.GetString("CarrelloVai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a il tuo Carrello è vuoto.
        /// </summary>
        public static string CarrelloVuoto {
            get {
                return ResourceManager.GetString("CarrelloVuoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Causale.
        /// </summary>
        public static string Causale {
            get {
                return ResourceManager.GetString("Causale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ciao.
        /// </summary>
        public static string Ciao {
            get {
                return ResourceManager.GetString("Ciao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cognome.
        /// </summary>
        public static string Cognome {
            get {
                return ResourceManager.GetString("Cognome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Collezione 2024.
        /// </summary>
        public static string Collezione {
            get {
                return ResourceManager.GetString("Collezione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Carte.
        /// </summary>
        public static string Completa_Carte {
            get {
                return ResourceManager.GetString("Completa_Carte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Contanti.
        /// </summary>
        public static string Completa_Contanti {
            get {
                return ResourceManager.GetString("Completa_Contanti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Metodo di Pagamento:.
        /// </summary>
        public static string Completa_Metodo {
            get {
                return ResourceManager.GetString("Completa_Metodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Scrivi la cifra che inserisci per un eventuale resto..
        /// </summary>
        public static string Completa_resto {
            get {
                return ResourceManager.GetString("Completa_resto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Servizio:.
        /// </summary>
        public static string Completa_Servizio {
            get {
                return ResourceManager.GetString("Completa_Servizio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Servizio Consegna:.
        /// </summary>
        public static string Completa_ServizioDelivery {
            get {
                return ResourceManager.GetString("Completa_ServizioDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sub-Totale:.
        /// </summary>
        public static string Completa_Subtot {
            get {
                return ResourceManager.GetString("Completa_Subtot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Riepilogo Dati Ordine.
        /// </summary>
        public static string Completa_titolo {
            get {
                return ResourceManager.GetString("Completa_titolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Totale:.
        /// </summary>
        public static string Completa_totale {
            get {
                return ResourceManager.GetString("Completa_totale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Consegna.
        /// </summary>
        public static string Consegna {
            get {
                return ResourceManager.GetString("Consegna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cap.
        /// </summary>
        public static string Consegna_Cap {
            get {
                return ResourceManager.GetString("Consegna_Cap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cellulare.
        /// </summary>
        public static string Consegna_Cellullare {
            get {
                return ResourceManager.GetString("Consegna_Cellullare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Città.
        /// </summary>
        public static string Consegna_Citta {
            get {
                return ResourceManager.GetString("Consegna_Citta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Indirizzo.
        /// </summary>
        public static string Consegna_Indirizzo {
            get {
                return ResourceManager.GetString("Consegna_Indirizzo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nome e Cognome.
        /// </summary>
        public static string Consegna_Nominativo {
            get {
                return ResourceManager.GetString("Consegna_Nominativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Provincia.
        /// </summary>
        public static string Consegna_Provincia {
            get {
                return ResourceManager.GetString("Consegna_Provincia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Inserisci i dati per la consegna.
        /// </summary>
        public static string Consegna_titolo {
            get {
                return ResourceManager.GetString("Consegna_titolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Contatta per il prezzo.
        /// </summary>
        public static string ContattaPrezzo {
            get {
                return ResourceManager.GetString("ContattaPrezzo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Contattaci.
        /// </summary>
        public static string Contatti {
            get {
                return ResourceManager.GetString("Contatti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Continua lo Shopping.
        /// </summary>
        public static string ContinuaShopping {
            get {
                return ResourceManager.GetString("ContinuaShopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Data ordine.
        /// </summary>
        public static string Data_ordine {
            get {
                return ResourceManager.GetString("Data_ordine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Data dell&apos;ordine.
        /// </summary>
        public static string DataOrdine {
            get {
                return ResourceManager.GetString("DataOrdine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a I tuoi dati personali.
        /// </summary>
        public static string DatiPersonali {
            get {
                return ResourceManager.GetString("DatiPersonali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a I tuoi dati di spedizione.
        /// </summary>
        public static string DatiSpedizione {
            get {
                return ResourceManager.GetString("DatiSpedizione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Dettaglio.
        /// </summary>
        public static string Dettaglio {
            get {
                return ResourceManager.GetString("Dettaglio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a I dettagli del tuo ordine.
        /// </summary>
        public static string DettagliOrdine {
            get {
                return ResourceManager.GetString("DettagliOrdine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a di.
        /// </summary>
        public static string Di {
            get {
                return ResourceManager.GetString("Di", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a  &lt;h1&gt;
        ///     Informativa sui rimborsi
        /// &lt;/h1&gt;
        /// &lt;br /&gt;
        /// &lt;p class=&quot;par-index&quot;&gt;
        ///     &lt;b&gt;Diritti di recesso e resi&lt;/b&gt;&lt;br /&gt;&lt;br /&gt;
        ///     - Il prodotto arrivato non vi piace, non è della misura giusta o presenta dei difetti di fabbrica?&lt;br /&gt;&lt;br /&gt;
        ///     La nostra politica di reso e recesso prevede che se il cliente non è soddisfatto al 100% di uno qualsiasi dei prodotti ordinati, saremo felici di
        ///     rimborsarlo.&lt;br /&gt;
        ///     - Il cliente può esercitare il reso dei prodotti entro &lt;b&gt;14 giorni&lt;/b&gt; di calendar [stringa troncata]&quot;;.
        /// </summary>
        public static string DirittoDiRecesso {
            get {
                return ResourceManager.GetString("DirittoDiRecesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Email o Password non riconosciute.
        /// </summary>
        public static string email_pass_no {
            get {
                return ResourceManager.GetString("email_pass_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Inserire Email per recupera la password.
        /// </summary>
        public static string email_per_recupero {
            get {
                return ResourceManager.GetString("email_per_recupero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gli eventuali sconti saranno calcolati al momento del checkout.
        /// </summary>
        public static string Eventuali_sconti {
            get {
                return ResourceManager.GetString("Eventuali_sconti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Privacy e GDPR.
        /// </summary>
        public static string GPDRPriv {
            get {
                return ResourceManager.GetString("GPDRPriv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Grazie per il tuo ordine. Ti abbiamo inviato una email con i dati per effettuare il pagamento tramite il metodo scelto..
        /// </summary>
        public static string GrazieBonificoPar {
            get {
                return ResourceManager.GetString("GrazieBonificoPar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Grazie per il tuo ordine. Riceverai una email di conferma con i dettagli dell&apos;ordine..
        /// </summary>
        public static string GrazieOrdine {
            get {
                return ResourceManager.GetString("GrazieOrdine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Guida alle taglie.
        /// </summary>
        public static string GuidaTaglie {
            get {
                return ResourceManager.GetString("GuidaTaglie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Asporto.
        /// </summary>
        public static string Home_Asporto {
            get {
                return ResourceManager.GetString("Home_Asporto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Benvenuto al ristorante 081Lab.
        /// </summary>
        public static string Home_Benvenuto {
            get {
                return ResourceManager.GetString("Home_Benvenuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Consegna.
        /// </summary>
        public static string Home_Consegna {
            get {
                return ResourceManager.GetString("Home_Consegna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Siediti al Tavolo.
        /// </summary>
        public static string Home_Servizio {
            get {
                return ResourceManager.GetString("Home_Servizio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Immagine.
        /// </summary>
        public static string Immagine {
            get {
                return ResourceManager.GetString("Immagine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a     &lt;br /&gt;
        ///    &lt;div class=&quot;col-lg-6&quot;&gt;
        ///        &lt;p class=&quot;par-index&quot;&gt;
        ///            &lt;b&gt;ITALIA&lt;/b&gt;&lt;br /&gt;
        ///            La spedizione per il territorio nazionale italiano è pari a 7,00 € per prodotto.&lt;br /&gt;
        ///&lt;br /&gt;
        ///           
        ///            &lt;br /&gt;&lt;br /&gt;
        ///
        ///        &lt;/p&gt;
        ///    &lt;/div&gt;
        ///
        ///&lt;/div&gt;
        ///&lt;p class=&quot;par-index&quot;&gt;
        ///
        ///
        ///    &lt;b&gt;NOTA:&lt;/b&gt; Eventuali Oneri O Dazi Doganali Sono Da Ritenersi A Carico Del Destinatario
        ///    &lt;br /&gt;&lt;br /&gt;
        ///
        ///&lt;/p&gt;.
        /// </summary>
        public static string InformativaSpedizioni {
            get {
                return ResourceManager.GetString("InformativaSpedizioni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Inizia ad acquistare.
        /// </summary>
        public static string Inizia {
            get {
                return ResourceManager.GetString("Inizia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Intestatario.
        /// </summary>
        public static string Intestatario {
            get {
                return ResourceManager.GetString("Intestatario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invia.
        /// </summary>
        public static string Invia {
            get {
                return ResourceManager.GetString("Invia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a  &lt;h1 style=&quot;text-align:end&quot;&gt;
        ///     Istruzioni per la spedizione di rientro
        /// &lt;/h1&gt;
        /// &lt;br /&gt;
        /// &lt;p class=&quot;par-index &quot; style=&quot;&quot;&gt;
        ///     &lt;b&gt;Per avvalersi del diritto di reso e/o di recesso seguite questi semplici passaggi.&lt;/b&gt;&lt;br /&gt;&lt;br /&gt;
        ///     Contattare Forrest sul link &lt;b&gt;Supporto WhatsApp 24/7.&lt;/b&gt;&lt;br /&gt;&lt;br /&gt;
        ///     Impacchettare gli articoli nel suo imballo originale.&lt;br /&gt;&lt;br /&gt;
        ///     Spedire il pacco all&apos;indirizzo seguente: &lt;b&gt;Sartoria Forrest, Via Cupa Cesa n°2, 81030 Succivo CE&lt;/b&gt;&lt;br /&gt;&lt;br /&gt;
        ///     Ti  [stringa troncata]&quot;;.
        /// </summary>
        public static string IstruzioniReso {
            get {
                return ResourceManager.GetString("IstruzioniReso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a I tuoi Ordini.
        /// </summary>
        public static string ItuoiOrdini {
            get {
                return ResourceManager.GetString("ItuoiOrdini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Linea sartoriale.
        /// </summary>
        public static string LineaSartoriale {
            get {
                return ResourceManager.GetString("LineaSartoriale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Negli anni ’80&apos; vendeva abiti di alta sartoria in tutto il mondo. E’ la storia di Alessio D&apos;Ambra, fondatore di &quot;Sartoria Forrest&quot;,
        ///un’azienda che, da anni,
        ///si occupa di abbigliamento, soprattutto maschile,
        ///lavorato a mano, con rifiniture curatissime e ormai presente in tutto il mondo..
        /// </summary>
        public static string LineaSartorialePar {
            get {
                return ResourceManager.GetString("LineaSartorialePar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Linea Sartoriale.
        /// </summary>
        public static string LineaSartorialeTitle {
            get {
                return ResourceManager.GetString("LineaSartorialeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Mappa del sito.
        /// </summary>
        public static string Mappa {
            get {
                return ResourceManager.GetString("Mappa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Meno costoso.
        /// </summary>
        public static string MenoCostoso {
            get {
                return ResourceManager.GetString("MenoCostoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Messaggio.
        /// </summary>
        public static string Messaggio {
            get {
                return ResourceManager.GetString("Messaggio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nazione.
        /// </summary>
        public static string Nazione {
            get {
                return ResourceManager.GetString("Nazione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Negozi.
        /// </summary>
        public static string Negozi {
            get {
                return ResourceManager.GetString("Negozi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Non hai ancora effettutato ordini.
        /// </summary>
        public static string No_ord_yet {
            get {
                return ResourceManager.GetString("No_ord_yet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nome.
        /// </summary>
        public static string Nome {
            get {
                return ResourceManager.GetString("Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nome Banca.
        /// </summary>
        public static string Nome_Banca {
            get {
                return ResourceManager.GetString("Nome_Banca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Configurazione incompleta o prodotto non disponibile..
        /// </summary>
        public static string NonDisponibile {
            get {
                return ResourceManager.GetString("NonDisponibile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Non hai un account? Registrati.
        /// </summary>
        public static string NonHaiAccount {
            get {
                return ResourceManager.GetString("NonHaiAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a La Nostra Azienda.
        /// </summary>
        public static string NostraAzienda {
            get {
                return ResourceManager.GetString("NostraAzienda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Numero Ordine.
        /// </summary>
        public static string Numero_ordine {
            get {
                return ResourceManager.GetString("Numero_ordine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Numero  Tavolo.
        /// </summary>
        public static string Numero_Tavolo {
            get {
                return ResourceManager.GetString("Numero_Tavolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nuovi prodotti.
        /// </summary>
        public static string Nuovi {
            get {
                return ResourceManager.GetString("Nuovi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Offerte.
        /// </summary>
        public static string Offerte {
            get {
                return ResourceManager.GetString("Offerte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ordina per:.
        /// </summary>
        public static string OrdinaPer {
            get {
                return ResourceManager.GetString("OrdinaPer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Grazie per l&apos;acquisto.
        /// </summary>
        public static string OrdineCompletato {
            get {
                return ResourceManager.GetString("OrdineCompletato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ordine confermato.
        /// </summary>
        public static string OrdineConfermato {
            get {
                return ResourceManager.GetString("OrdineConfermato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ordine Inviato.
        /// </summary>
        public static string OrdineInviato {
            get {
                return ResourceManager.GetString("OrdineInviato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tavoli.
        /// </summary>
        public static string Ordini_Tavoli {
            get {
                return ResourceManager.GetString("Ordini_Tavoli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tavolo.
        /// </summary>
        public static string Ordini_Tavolo {
            get {
                return ResourceManager.GetString("Ordini_Tavolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Paga con:.
        /// </summary>
        public static string PagaCon {
            get {
                return ResourceManager.GetString("PagaCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Pagamento Sicuro.
        /// </summary>
        public static string PagaSicuro {
            get {
                return ResourceManager.GetString("PagaSicuro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Pagato con.
        /// </summary>
        public static string PagatoCon {
            get {
                return ResourceManager.GetString("PagatoCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a parziale.
        /// </summary>
        public static string parziale {
            get {
                return ResourceManager.GetString("parziale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Password dimenticata?.
        /// </summary>
        public static string Pass_dimenticata {
            get {
                return ResourceManager.GetString("Pass_dimenticata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Password recuperata correttamente a breve riceverai una mail con la nuova password..
        /// </summary>
        public static string Pass_recuperata {
            get {
                return ResourceManager.GetString("Pass_recuperata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Metodo di pagamento.
        /// </summary>
        public static string Pay_met {
            get {
                return ResourceManager.GetString("Pay_met", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Per effettuare i pagamenti tramite bonifico utilizzare i seguenti dati:.
        /// </summary>
        public static string Per_Pagare {
            get {
                return ResourceManager.GetString("Per_Pagare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Più costoso.
        /// </summary>
        public static string PiuCostoso {
            get {
                return ResourceManager.GetString("PiuCostoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Più Venduti.
        /// </summary>
        public static string PiuVenduti {
            get {
                return ResourceManager.GetString("PiuVenduti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Politica di Reso.
        /// </summary>
        public static string PoliticadiReso {
            get {
                return ResourceManager.GetString("PoliticadiReso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Prodotti.
        /// </summary>
        public static string Prodotti {
            get {
                return ResourceManager.GetString("Prodotti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Prodotto.
        /// </summary>
        public static string Prodotto {
            get {
                return ResourceManager.GetString("Prodotto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Prodotti visualizzati:.
        /// </summary>
        public static string ProdottoVisualizzati {
            get {
                return ResourceManager.GetString("ProdottoVisualizzati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Profilo.
        /// </summary>
        public static string Profilo {
            get {
                return ResourceManager.GetString("Profilo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Q.ta.
        /// </summary>
        public static string Qta {
            get {
                return ResourceManager.GetString("Qta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Quantità.
        /// </summary>
        public static string Quantita {
            get {
                return ResourceManager.GetString("Quantita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Registrati.
        /// </summary>
        public static string Registrati {
            get {
                return ResourceManager.GetString("Registrati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Registrazione avvenuta con successo. Ti abbiamo mandato una email con i dati usati in fase di registrazione.
        /// </summary>
        public static string Registrazione_avvenuta {
            get {
                return ResourceManager.GetString("Registrazione_avvenuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ricordami.
        /// </summary>
        public static string Ricordami {
            get {
                return ResourceManager.GetString("Ricordami", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a FINO ALL&apos; 85% DI SCONTO.
        /// </summary>
        public static string Sconti {
            get {
                return ResourceManager.GetString("Sconti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a fino al 30% di sconto.
        /// </summary>
        public static string Sconto {
            get {
                return ResourceManager.GetString("Sconto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Scrivici.
        /// </summary>
        public static string Scrivici {
            get {
                return ResourceManager.GetString("Scrivici", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Seleziona taglia.
        /// </summary>
        public static string SelezionaTaglia {
            get {
                return ResourceManager.GetString("SelezionaTaglia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Inserisci il numero del tavolo.
        /// </summary>
        public static string Servizio_titolo {
            get {
                return ResourceManager.GetString("Servizio_titolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Abiti da cerimonia &lt;span style=&quot;color:gray&quot;&gt;2025&lt;/span&gt;.
        /// </summary>
        public static string sicure {
            get {
                return ResourceManager.GetString("sicure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a  &lt;h1 style=&quot;text-align:center&quot;&gt;
        ///     PAGAMENTI E SICUREZZA PAGAMENTI
        /// &lt;/h1&gt;
        /// &lt;br /&gt;
        /// &lt;p class=&quot;par-index &quot; style=&quot;&quot;&gt;
        ///     I metodi di pagamento accettati sono i seguenti:&lt;br /&gt;&lt;br /&gt;
        ///     Carte di credito e carte prepagate registrate al circuito PayPal.&lt;br /&gt;&lt;br /&gt;
        ///     Tutte le transazioni sono processate tramite server sicuro, garantendo ai clienti la massima protezione dei dati.&lt;br /&gt;&lt;br /&gt;
        ///     Scegliendo il metodo di pagamento PayPal i clienti potranno pagare direttamente tramite il proprio con [stringa troncata]&quot;;.
        /// </summary>
        public static string SicurezzaPagamenti {
            get {
                return ResourceManager.GetString("SicurezzaPagamenti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Spese di spedizione.
        /// </summary>
        public static string SpeseDiSpedizione {
            get {
                return ResourceManager.GetString("SpeseDiSpedizione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Taglia.
        /// </summary>
        public static string Taglia {
            get {
                return ResourceManager.GetString("Taglia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &lt;p class=&quot;par-index&quot;&gt;
        ///    &lt;b&gt;Tempi di spedizione&lt;/b&gt;&lt;br /&gt;
        ///    Gli ordini sono spediti da PlexEvolution, dal Lunedì al Venerdì con orario 9:00 - 17:00.&lt;br /&gt;
        ///    Gli ordini pervenuti dalle ore 13:00 di Venerdì, del Sabato e la Domenica verranno spediti il Lunedì successivo.&lt;br /&gt;
        ///    Per gli articoli disponibili la spedizione sarà effettuata di norma entro 24h/48h. Riceverà il suo ordine entro 5/7 giorni lavorativi dal momento della
        ///    spedizione.&lt;br /&gt;&lt;br /&gt;
        ///    &lt;b&gt;Rintracciabilità della spedizione&lt; [stringa troncata]&quot;;.
        /// </summary>
        public static string TempiSpedizione {
            get {
                return ResourceManager.GetString("TempiSpedizione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a                 Informativa sulle spedizioni
        ///.
        /// </summary>
        public static string TitoloConsegne {
            get {
                return ResourceManager.GetString("TitoloConsegne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Torna Agli Acquisti.
        /// </summary>
        public static string TornaAgliAcquisti {
            get {
                return ResourceManager.GetString("TornaAgliAcquisti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Torna alla lista degli ordini.
        /// </summary>
        public static string TornaAOrdini {
            get {
                return ResourceManager.GetString("TornaAOrdini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Torna alla Home.
        /// </summary>
        public static string TornaHome {
            get {
                return ResourceManager.GetString("TornaHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Prezzo Totale.
        /// </summary>
        public static string Totale {
            get {
                return ResourceManager.GetString("Totale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Totale dell&apos;ordine.
        /// </summary>
        public static string TotaleOrdine {
            get {
                return ResourceManager.GetString("TotaleOrdine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Prezzo Unitario.
        /// </summary>
        public static string Unitario {
            get {
                return ResourceManager.GetString("Unitario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Utente non riconosciuto, riprovare.
        /// </summary>
        public static string utente_no {
            get {
                return ResourceManager.GetString("utente_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Valorizzare tutti i campi obbligatori, incluso il CAP..
        /// </summary>
        public static string valida_form {
            get {
                return ResourceManager.GetString("valida_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a L&apos;indirizzo deve contenere anche il numero civico. Esempio: Via Roma 10..
        /// </summary>
        public static string valida_indirizzo {
            get {
                return ResourceManager.GetString("valida_indirizzo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Vedi.
        /// </summary>
        public static string Vedi {
            get {
                return ResourceManager.GetString("Vedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Supporto WhatsApp 24/7.
        /// </summary>
        public static string Whatsapp {
            get {
                return ResourceManager.GetString("Whatsapp", resourceCulture);
            }
        }
    }
}
