//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alimenti
    {
        public int id_alimento { get; set; }
        public string Descrizione { get; set; }
        public Nullable<bool> Allergeni { get; set; }
        public string Path_icon { get; set; }
        public string Descrizione_eng { get; set; }
    }
}
