//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlimentiProdotto
    {
        public int id_alimento_prodotto { get; set; }
        public int id_prodotto { get; set; }
        public int id_alimento { get; set; }
        public string Percentuale { get; set; }
        public string LottoAlimento { get; set; }
        public bool Congelato { get; set; }
    }
}
