//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnnulloScontrino
    {
        public int id_annullo { get; set; }
        public string codiceAzzeramento { get; set; }
        public string codiceScontrino { get; set; }
        public string gestionale { get; set; }
        public System.DateTime dataInserimento { get; set; }
        public bool DaAnnullare { get; set; }
        public System.DateTime DataScontrino { get; set; }
    }
}
