//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssociazioneStampantiCategorie
    {
        public int id_stampante_categoria { get; set; }
        public Nullable<int> stampante { get; set; }
        public Nullable<int> categoria { get; set; }
        public bool eliminato { get; set; }
    }
}
