//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Associazione_Prodotto_Collezione
    {
        public int Id_ass_prodotto_collezione { get; set; }
        public Nullable<int> id_prodotto { get; set; }
        public Nullable<int> id_collezione { get; set; }
    }
}
