//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Associazioni_prodotti
    {
        public int id_associazione_prodotti { get; set; }
        public int Id_prodotto { get; set; }
        public int Id_propieta { get; set; }
        public int id_valore { get; set; }
        public string Descrizione { get; set; }
        public Nullable<double> ValoreDaAggiungere { get; set; }
        public string Path_img { get; set; }
    }
}
