//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categorie
    {
        public int id_categorie { get; set; }
        public string Descrizione { get; set; }
        public string PathIcona { get; set; }
        public string PathCopertina { get; set; }
        public bool eliminato { get; set; }
        public bool Servizio { get; set; }
        public string Descrizione_eng { get; set; }
        public string Colore_categoria { get; set; }
        public bool MostraWeb { get; set; }
        public Nullable<int> posizione { get; set; }
        public Nullable<bool> is_collezione { get; set; }
        public Nullable<bool> is_evidenza { get; set; }
        public List<Sottocategorie> ListaSottocategorie { get; set; }

    }
}
