//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodiciSconto
    {
        public int id_codice_sconto { get; set; }
        public string codice_sconto { get; set; }
        public Nullable<double> percentuale { get; set; }
        public Nullable<double> valore { get; set; }
        public Nullable<System.DateTime> data_fine { get; set; }
        public Nullable<int> id_utente { get; set; }
        public Nullable<bool> utilizzato { get; set; }
        public Nullable<System.DateTime> data_utilizzo { get; set; }
        public Nullable<int> id_tipoSconto { get; set; }
        public string Descrizione { get; set; }
        public string NomeUtente { get; set; }
        public Nullable<bool> ScontoPrimoOrdine { get; set; }
    }
}
