//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comuni
    {
        public int id_comune { get; set; }
        public string Descrizione_Comune { get; set; }
        public string Sigla { get; set; }
        public string Codice_Elettorale { get; set; }
        public string Codice_instat { get; set; }
        public string Codice_Belfiore { get; set; }
        public bool Isola { get; set; }
    }
}
