//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigurazioneNegozio
    {
        public int idConfigurazioneNegozio { get; set; }
        public string NomeNegozio { get; set; }
        public bool Aperto { get; set; }
        public Nullable<System.TimeSpan> OrarioInizio_pranzo { get; set; }
        public Nullable<System.TimeSpan> OrarioFine_pranzo { get; set; }
        public Nullable<System.TimeSpan> OrarioInizioCena { get; set; }
        public Nullable<System.TimeSpan> OrarioFineCena { get; set; }
        public string GiorniApertura { get; set; }
    }
}
