//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigurazioneCassa
    {
        public int id_configurazione_cassa { get; set; }
        public bool chiudicassa { get; set; }
        public System.DateTime dataChiusura { get; set; }
        public bool LetturaCassa { get; set; }
        public bool ScontrinoRegalo { get; set; }
    }
}
