//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AnyeLabelEntities : DbContext
    {
        public AnyeLabelEntities()
            : base("name=AnyeLabelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alimenti> Alimenti { get; set; }
        public virtual DbSet<AlimentiProdotto> AlimentiProdotto { get; set; }
        public virtual DbSet<AnnulloScontrino> AnnulloScontrino { get; set; }
        public virtual DbSet<Associazione_Prodotto_Collezione> Associazione_Prodotto_Collezione { get; set; }
        public virtual DbSet<AssociazioneStampantiCategorie> AssociazioneStampantiCategorie { get; set; }
        public virtual DbSet<Associazioni_prodotti> Associazioni_prodotti { get; set; }
        public virtual DbSet<Cat_SubCat> Cat_SubCat { get; set; }
        public virtual DbSet<Categorie> Categorie { get; set; }
        public virtual DbSet<CategorieFattura> CategorieFattura { get; set; }
        public virtual DbSet<Codici> Codici { get; set; }
        public virtual DbSet<CodiciSconto> CodiciSconto { get; set; }
        public virtual DbSet<Colori> Colori { get; set; }
        public virtual DbSet<Comuni> Comuni { get; set; }
        public virtual DbSet<ConfigurazioneCassa> ConfigurazioneCassa { get; set; }
        public virtual DbSet<ConfigurazioneNegozio> ConfigurazioneNegozio { get; set; }
        public virtual DbSet<Eventi> Eventi { get; set; }
        public virtual DbSet<Fascia_Oraria> Fascia_Oraria { get; set; }
        public virtual DbSet<Fatture> Fatture { get; set; }
        public virtual DbSet<Fornitori> Fornitori { get; set; }
        public virtual DbSet<GestioneAppuntamenti> GestioneAppuntamenti { get; set; }
        public virtual DbSet<GestioneTavoli> GestioneTavoli { get; set; }
        public virtual DbSet<GruppoColori> GruppoColori { get; set; }
        public virtual DbSet<GruppoColori_Colori> GruppoColori_Colori { get; set; }
        public virtual DbSet<GruppoSpessori> GruppoSpessori { get; set; }
        public virtual DbSet<GruppoSpessori_Spessore> GruppoSpessori_Spessore { get; set; }
        public virtual DbSet<GruppoTaglia> GruppoTaglia { get; set; }
        public virtual DbSet<GruppoTaglia_Taglie> GruppoTaglia_Taglie { get; set; }
        public virtual DbSet<Immagini_catProd> Immagini_catProd { get; set; }
        public virtual DbSet<LogTransazioni> LogTransazioni { get; set; }
        public virtual DbSet<Marche> Marche { get; set; }
        public virtual DbSet<Marchi> Marchi { get; set; }
        public virtual DbSet<Modello> Modello { get; set; }
        public virtual DbSet<MovimentiMagazzino> MovimentiMagazzino { get; set; }
        public virtual DbSet<Ordine> Ordine { get; set; }
        public virtual DbSet<Preventivi> Preventivi { get; set; }
        public virtual DbSet<Prodotti> Prodotti { get; set; }
        public virtual DbSet<ProdottiOrdine> ProdottiOrdine { get; set; }
        public virtual DbSet<ProdottiTag> ProdottiTag { get; set; }
        public virtual DbSet<ProdottoTaglia> ProdottoTaglia { get; set; }
        public virtual DbSet<Ruoli> Ruoli { get; set; }
        public virtual DbSet<ScontiSpec_Cat> ScontiSpec_Cat { get; set; }
        public virtual DbSet<ScontiSpeciali> ScontiSpeciali { get; set; }
        public virtual DbSet<Slider> Slider { get; set; }
        public virtual DbSet<Sottocategorie> Sottocategorie { get; set; }
        public virtual DbSet<Spessori> Spessori { get; set; }
        public virtual DbSet<Stampanti> Stampanti { get; set; }
        public virtual DbSet<Stato_Ordine> Stato_Ordine { get; set; }
        public virtual DbSet<Stato_Pagamento> Stato_Pagamento { get; set; }
        public virtual DbSet<StatoTavolo> StatoTavolo { get; set; }
        public virtual DbSet<StoricoFatturato> StoricoFatturato { get; set; }
        public virtual DbSet<TabellaOrdiniTavolo> TabellaOrdiniTavolo { get; set; }
        public virtual DbSet<Tag> Tag { get; set; }
        public virtual DbSet<Taglie> Taglie { get; set; }
        public virtual DbSet<Tavoli> Tavoli { get; set; }
        public virtual DbSet<TavoliOrdini> TavoliOrdini { get; set; }
        public virtual DbSet<TestiHome> TestiHome { get; set; }
        public virtual DbSet<Tipi_Immagini> Tipi_Immagini { get; set; }
        public virtual DbSet<Tipi_Vendita> Tipi_Vendita { get; set; }
        public virtual DbSet<TipiSconto> TipiSconto { get; set; }
        public virtual DbSet<Tipo_Fatture> Tipo_Fatture { get; set; }
        public virtual DbSet<TipoMovimentoMagazzino> TipoMovimentoMagazzino { get; set; }
        public virtual DbSet<TipoOrdine> TipoOrdine { get; set; }
        public virtual DbSet<TipoStampante> TipoStampante { get; set; }
        public virtual DbSet<Toolbar> Toolbar { get; set; }
        public virtual DbSet<Utenti> Utenti { get; set; }
        public virtual DbSet<TipoPagamento> TipoPagamento { get; set; }
        public virtual DbSet<DettaglioAssociazioneStampantiCategorie> DettaglioAssociazioneStampantiCategorie { get; set; }
        public virtual DbSet<DettaglioFatture> DettaglioFatture { get; set; }
        public virtual DbSet<DettaglioGestioneTavoli> DettaglioGestioneTavoli { get; set; }
        public virtual DbSet<DettaglioGestioneTavoliReport> DettaglioGestioneTavoliReport { get; set; }
        public virtual DbSet<DettaglioGruppoColori> DettaglioGruppoColori { get; set; }
        public virtual DbSet<DettaglioGruppoSpessori> DettaglioGruppoSpessori { get; set; }
        public virtual DbSet<DettaglioGruppoTaglie> DettaglioGruppoTaglie { get; set; }
        public virtual DbSet<DettaglioModelli> DettaglioModelli { get; set; }
        public virtual DbSet<DettaglioOrdiniTavolo> DettaglioOrdiniTavolo { get; set; }
        public virtual DbSet<DettaglioProdotti> DettaglioProdotti { get; set; }
        public virtual DbSet<DettaglioProdottiOrdine> DettaglioProdottiOrdine { get; set; }
        public virtual DbSet<DettaglioProdottiTaglie> DettaglioProdottiTaglie { get; set; }
        public virtual DbSet<DettagliOrdine> DettagliOrdine { get; set; }
        public virtual DbSet<DettaglioReport> DettaglioReport { get; set; }
        public virtual DbSet<DettaglioReportProdotti> DettaglioReportProdotti { get; set; }
        public virtual DbSet<DettaglioStampanti> DettaglioStampanti { get; set; }
        public virtual DbSet<DettaglioTavoli> DettaglioTavoli { get; set; }
        public virtual DbSet<Lista_Utenti> Lista_Utenti { get; set; }
        public virtual DbSet<View_Collezioni_Prodotti> View_Collezioni_Prodotti { get; set; }
        public virtual DbSet<View_DettaglioAlimentiProdotto> View_DettaglioAlimentiProdotto { get; set; }
        public virtual DbSet<View_DettaglioFornitori> View_DettaglioFornitori { get; set; }
        public virtual DbSet<View_DettaglioMovimentiMagazzino> View_DettaglioMovimentiMagazzino { get; set; }
        public virtual DbSet<View_ProdPiuVenduti> View_ProdPiuVenduti { get; set; }
        public virtual DbSet<Vista_Preventivi> Vista_Preventivi { get; set; }
    }
}
