//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;

    public partial class DettaglioGruppoTaglie
    {
        public int id_gruppoTaglia { get; set; }
        public string Descrizione_gruppo { get; set; }
        public string taglie { get; set; }
        public string taglie_ids { get; set; }
        public List<int> taglie_ids_int { get; set; }
    }
}
