//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DettaglioProdotti
    {
        public int id_prodotto { get; set; }
        public string Descrizione { get; set; }
        public int id_categoria { get; set; }
        public Nullable<int> id_Marca { get; set; }
        public string pathFoto { get; set; }
        public Nullable<double> PrezzoAcquisto { get; set; }
        public Nullable<double> PrezzoVendita { get; set; }
        public Nullable<double> iva { get; set; }
        public int Quantita { get; set; }
        public string Ingredienti { get; set; }
        public bool eliminato { get; set; }
        public Nullable<bool> IsSpecial { get; set; }
        public string BarCode { get; set; }
        public string LottoProdotto { get; set; }
        public Nullable<System.DateTime> DataProduzione { get; set; }
        public Nullable<System.DateTime> DataScadenza { get; set; }
        public string Ingredienti_eng { get; set; }
        public string DescrizioneProdotto_eng { get; set; }
        public bool MostraWeb { get; set; }
        public string Categoria { get; set; }
        public string Categoria_eng { get; set; }
        public string PathIcona { get; set; }
        public string Nome { get; set; }
        public string Marca { get; set; }
        public string taglie { get; set; }
        public string id_taglie { get; set; }
        public string offerta { get; set; }
    }
}
