//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DettaglioFatture
    {
        public int id_fatture { get; set; }
        public int id_categoria { get; set; }
        public int Id_tipo { get; set; }
        public int id_fornitore { get; set; }
        public string CategoriaFattura { get; set; }
        public string TipoFattura { get; set; }
        public System.DateTime Data { get; set; }
        public double Valore { get; set; }
        public string RagioneSociale { get; set; }
        public string PartitaIva { get; set; }
        public string numeroFattura { get; set; }
        public string indirizzo { get; set; }
        public string num_Telefono { get; set; }
        public string Email { get; set; }
    }
}
