//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DettaglioReportProdotti
    {
        public int id_ordine { get; set; }
        public int id_prodotto { get; set; }
        public Nullable<int> id_stato { get; set; }
        public bool is_servizio { get; set; }
        public string Descrizione { get; set; }
        public int Quantita { get; set; }
        public string DescrizioneCategoria { get; set; }
        public System.DateTime DataOra { get; set; }
        public Nullable<int> NumeroPezzi { get; set; }
    }
}
