//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DettaglioReport
    {
        public int id_ordine { get; set; }
        public Nullable<int> id_stato { get; set; }
        public Nullable<int> id_tipoVendita { get; set; }
        public Nullable<int> id_prodotto { get; set; }
        public Nullable<int> Quantita { get; set; }
        public System.DateTime DataOra { get; set; }
        public Nullable<double> Totale { get; set; }
        public Nullable<double> sconto { get; set; }
        public Nullable<bool> is_servizio { get; set; }
        public string prodotto { get; set; }
        public Nullable<int> id_categoria { get; set; }
        public string categoria { get; set; }
    }
}
