//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;

    public partial class DettaglioGruppoSpessori
    {
        public int id_gruppoSpessori { get; set; }
        public string Descrizione_gruppo { get; set; }
        public string spessori { get; set; }
        public string spessori_ids { get; set; }
        public List<int> spessori_ids_int { get; set; }

    }
}
