//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DettaglioGestioneTavoliReport
    {
        public int id_gestione { get; set; }
        public int id_tavolo { get; set; }
        public Nullable<int> id_utente { get; set; }
        public Nullable<int> id_stato { get; set; }
        public Nullable<int> numero_persone { get; set; }
        public Nullable<System.DateTime> data_prenotazione { get; set; }
        public bool stampa_preconto { get; set; }
        public bool chiuso { get; set; }
        public Nullable<double> totale { get; set; }
        public Nullable<double> percentuale_servizio { get; set; }
        public Nullable<bool> fiscale { get; set; }
        public string metodo_pagamento { get; set; }
        public Nullable<bool> stampa_fiscale { get; set; }
        public bool stampa_non_fiscale { get; set; }
        public string numeroTavolo { get; set; }
        public string Descrizione_stato { get; set; }
        public Nullable<double> sconto { get; set; }
        public string nome_prenotazione { get; set; }
        public bool Annullato { get; set; }
        public Nullable<int> id_prodotto { get; set; }
        public string Descrizione { get; set; }
        public Nullable<bool> Servizio { get; set; }
    }
}
