//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DettaglioTavoli
    {
        public int id_tavolo { get; set; }
        public string numero { get; set; }
        public string nome { get; set; }
        public bool eliminato { get; set; }
        public Nullable<int> id_gestione { get; set; }
        public Nullable<int> stato { get; set; }
        public Nullable<int> numero_persone { get; set; }
        public Nullable<System.DateTime> data_prenotazione { get; set; }
        public Nullable<bool> chiuso { get; set; }
        public string nome_prenotazione { get; set; }
        public Nullable<bool> preconto_stampato { get; set; }
        public Nullable<double> totale { get; set; }
        public Nullable<bool> Annullato { get; set; }
    }
}
