//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;

    public partial class DettaglioGruppoColori
    {
        public int id_gruppoColore { get; set; }
        public string Descrizione_gruppo { get; set; }
        public string colori { get; set; }
        public string colori_ids { get; set; }
        public List<int> colori_ids_int { get; set; }

    }
}
