//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;

    public partial class DettaglioProdottiOrdine
    {
        public int id_ProdottiOrdine { get; set; }
        public int id_prodotto { get; set; }
        public int id_ordine { get; set; }
        public int id_taglia { get; set; }
        public int Quantita { get; set; }
        public double prezzoUnitario { get; set; }
        public string Note { get; set; }
        public Nullable<double> iva { get; set; }
        public Nullable<double> Sconto { get; set; }
        public string NomeProdotto { get; set; }
        public Nullable<int> id_categoria { get; set; }
        public Nullable<int> id_Marca { get; set; }
        public Nullable<bool> is_servizio { get; set; }
        public string pathFoto { get; set; }
        public string Categoria { get; set; }
        public string Taglia { get; set; }
        public Nullable<System.DateTime> DataOra { get; set; }
        public string BarCode { get; set; }
        public Nullable<double> scontoProdotto { get; set; }
        public Nullable<bool> InOfferta { get; set; }
        public Nullable<int> id_colore { get; set; }
        public Nullable<int> id_spessore { get; set; }
        public string descrizione_spessore { get; set; }
        public string Descrizione_colore { get; set; }
        public double prezzoScontato { get; set; }
        public List<ProdottoTaglia> listaProdottiTaglia { get; set; }
        public Prodotti Prodotto { get; set; }
    }
}
