//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eventi
    {
        public int id_evento { get; set; }
        public System.DateTime Dal { get; set; }
        public Nullable<System.DateTime> Al { get; set; }
        public string Descrizione { get; set; }
        public string PathImmagine { get; set; }
        public string Descrizione_Breve { get; set; }
    }
}
