//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fornitori
    {
        public int id_fornitore { get; set; }
        public string Descrizione_fornitore { get; set; }
        public string Partita_iva { get; set; }
        public string indirizzo { get; set; }
        public string Cap { get; set; }
        public string Citta { get; set; }
        public string num_Telefono { get; set; }
        public string Email { get; set; }
        public string Iban { get; set; }
        public Nullable<int> id_referente { get; set; }
        public string Codice_univoco { get; set; }
        public string Sito_web { get; set; }
        public string pec { get; set; }
    }
}
