//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GestioneAppuntamenti
    {
        public int id_appuntamento { get; set; }
        public string cliente { get; set; }
        public Nullable<System.DateTime> data_appuntamento { get; set; }
        public Nullable<System.DateTime> ora_appuntamento { get; set; }
        public Nullable<long> numero_telefono { get; set; }
    }
}
