//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GruppoTaglia_Taglie
    {
        public int id_gruppoTaglia_taglie { get; set; }
        public int id_taglia { get; set; }
        public int id_gruppoTaglia { get; set; }
    }
}
