//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Immagini_catProd
    {
        public int id_immagini { get; set; }
        public Nullable<int> id_tipo_immagine { get; set; }
        public string path { get; set; }
        public string Descrizione { get; set; }
        public string Alt { get; set; }
        public string Link { get; set; }
        public Nullable<int> id_prod { get; set; }
        public Nullable<int> id_cat { get; set; }
        public Nullable<int> img_height { get; set; }
        public Nullable<int> img_width { get; set; }
        public Nullable<int> id_sottocategoria { get; set; }
    }
}
