//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lista_Utenti
    {
        public int id_utente { get; set; }
        public string Nome { get; set; }
        public string Cognome { get; set; }
        public string Cellulare { get; set; }
        public string Mail { get; set; }
        public int id_Ruolo { get; set; }
        public string Password { get; set; }
        public Nullable<bool> Consenso { get; set; }
        public Nullable<System.DateTime> DataConsenso { get; set; }
        public string p_iva { get; set; }
        public string NomeCompleto { get; set; }
        public string indirizzo { get; set; }
        public string Cap { get; set; }
        public string Citta { get; set; }
        public string Iban { get; set; }
        public string CodiceUnivoco { get; set; }
        public string pec { get; set; }
        public string SitoWeb { get; set; }
        public string Codice_Fiscale { get; set; }
        public string Nazione { get; set; }
        public string Denominazione { get; set; }
        public string SedeLegale { get; set; }
        public string Ruolo { get; set; }
    }
}
