//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogTransazioni
    {
        public int id_transazione { get; set; }
        public string ip { get; set; }
        public int id_utente { get; set; }
        public string descrizione { get; set; }
        public System.DateTime dataOperazione { get; set; }
        public string Esito { get; set; }
    }
}
