//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimentiMagazzino
    {
        public int id_movimenti_Magazzino { get; set; }
        public int id_utente { get; set; }
        public System.DateTime DataMovimento { get; set; }
        public int Id_tipoMovimento { get; set; }
        public int Quantita { get; set; }
        public int Id_prodotto { get; set; }
        public Nullable<double> Prezzo_prodotto { get; set; }
        public Nullable<int> id_Fornitore { get; set; }
    }
}
