//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;

    public partial class Ordine
    {
        public int id_ordine { get; set; }
        public System.DateTime DataOra { get; set; }
        public string Ip { get; set; }
        public Nullable<int> NumeroPezzi { get; set; }
        public Nullable<double> Totale { get; set; }
        public Nullable<int> Tavolo { get; set; }
        public string Indirizzo { get; set; }
        public string Nominativo { get; set; }
        public string NumTelefono { get; set; }
        public Nullable<int> id_utente { get; set; }
        public string Note { get; set; }
        public string Tipo_Pagamento { get; set; }
        public string Tipo_Vendita { get; set; }
        public Nullable<int> id_tipoVendita { get; set; }
        public Nullable<int> id_stato { get; set; }
        public string Citta { get; set; }
        public string Provincia { get; set; }
        public string Cap { get; set; }
        public string TipoOrdine { get; set; }
        public Nullable<int> NumeroPersone { get; set; }
        public Nullable<double> sconto { get; set; }
        public Nullable<int> id_fila { get; set; }
        public Nullable<int> Numero { get; set; }
        public string Lato { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DataRitiro { get; set; }
        public string FasciaOraria { get; set; }
        public Nullable<int> id_tipoOrdine { get; set; }
        public Nullable<int> id_tipoPagamento { get; set; }
        public Nullable<int> id_codiceSconto { get; set; }
        public Nullable<bool> Fatturato { get; set; }
        public string Nazione { get; set; }
        public Nullable<int> id_stato_pagmento { get; set; }
        public Nullable<double> totale_spedizione { get; set; }

        public string DescrizioneStato { get; set; }
        public string DescrizioneStatoPagamento { get; set; }
        public string NomeStato { get; set; }
        public string NomeStatoPagamento { get; set; }
    }
}
