//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preventivi
    {
        public int id_preventivo { get; set; }
        public int id_cliente { get; set; }
        public Nullable<int> id_ordine { get; set; }
        public Nullable<int> id_stato_pagamento { get; set; }
        public string descrizione { get; set; }
        public Nullable<double> sconto { get; set; }
        public Nullable<int> id_modalita_pagamento { get; set; }
        public string note { get; set; }
        public Nullable<double> totale_preventivo { get; set; }
        public bool annullato { get; set; }
        public System.DateTime data_attivita { get; set; }
        public int numero_fattura { get; set; }
        public Nullable<int> anno { get; set; }
        public string cliente_utilizzatore { get; set; }
        public Nullable<System.DateTime> data_prevista { get; set; }
        public Nullable<int> id_interno { get; set; }
        public Nullable<int> aliquota { get; set; }
        public Nullable<int> id_ordine_fornitore { get; set; }
    }
}
