//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdottoTaglia
    {
        public int id_prodottoTaglia { get; set; }
        public int id_prodotto { get; set; }
        public Nullable<int> id_taglia { get; set; }
        public bool eliminato { get; set; }
        public int quantita { get; set; }
        public double prezzo { get; set; }
        public string BarCode { get; set; }
        public Nullable<int> id_colore { get; set; }
        public Nullable<int> id_spessore { get; set; }
    }
}
