//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;

    public partial class ProdottiOrdine
    {
        public int id_ProdottiOrdine { get; set; }
        public int id_prodotto { get; set; }
        public int id_ordine { get; set; }
        public int Quantita { get; set; }
        public double prezzoUnitario { get; set; }
        public string Note { get; set; }
        public Nullable<double> iva { get; set; }
        public Nullable<int> OrdineUscita { get; set; }
        public string LivelloCottura { get; set; }
        public Nullable<int> id_gestione { get; set; }
        public Nullable<double> Sconto { get; set; }
        public Nullable<int> id_taglia { get; set; }
        public Nullable<int> id_colore { get; set; }
        public Nullable<int> id_spessore { get; set; }
        public Prodotti Prodotto { get; set; }
        public string Taglia { get; set; }
        public double prezzoScontato { get; set; }
    }
}
