//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prodotti
    {
        public int id_prodotto { get; set; }
        public string Descrizione { get; set; }
        public int id_categoria { get; set; }
        public Nullable<int> id_Marca { get; set; }
        public string pathFoto { get; set; }
        public Nullable<double> PrezzoAcquisto { get; set; }
        public Nullable<double> PrezzoVendita { get; set; }
        public Nullable<double> iva { get; set; }
        public int Quantita { get; set; }
        public string Ingredienti { get; set; }
        public bool eliminato { get; set; }
        public Nullable<bool> IsSpecial { get; set; }
        public string BarCode { get; set; }
        public string LottoProdotto { get; set; }
        public Nullable<System.DateTime> DataProduzione { get; set; }
        public Nullable<System.DateTime> DataScadenza { get; set; }
        public string Ingredienti_eng { get; set; }
        public string Descrizione_eng { get; set; }
        public string Versione { get; set; }
        public Nullable<int> Id_modello { get; set; }
        public bool is_servizio { get; set; }
        public bool MostraWeb { get; set; }
        public Nullable<int> id_sottocategoria { get; set; }
        public Nullable<int> id_gruppo_taglie { get; set; }
        public Nullable<bool> in_offerta { get; set; }
        public Nullable<System.DateTime> inizio_offerta { get; set; }
        public Nullable<System.DateTime> fine_offerta { get; set; }
        public Nullable<double> sconto { get; set; }
        public Nullable<bool> GoogleMerchantEnabled { get; set; }
        public Nullable<bool> prezzo_visibile { get; set; }
        public Nullable<double> scontoSpeciale { get; set; }
        public Nullable<double> sconto_3 { get; set; }
        public bool is_special_off { get; set; }
        public bool Popup { get; set; }
        public Nullable<int> id_gruppo_colori { get; set; }
        public Nullable<int> id_gruppo_spessori { get; set; }
    }
}
