//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScontiSpeciali
    {
        public int id_scontoSpeciale { get; set; }
        public Nullable<System.DateTime> Data_Inizio { get; set; }
        public Nullable<System.DateTime> Data_Fine { get; set; }
        public Nullable<double> Valore { get; set; }
        public bool Attivo { get; set; }
        public string Sconto_speciale { get; set; }
    }
}
