//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slider
    {
        public int id_immagine { get; set; }
        public string path_img_slider { get; set; }
        public bool eliminato { get; set; }
        public string Link { get; set; }
        public Nullable<byte> slider_num { get; set; }
        public Nullable<byte> posizione { get; set; }
        public Nullable<int> id_prodotto { get; set; }
        public Nullable<int> id_categoria { get; set; }
        public string type { get; set; }
        public string Descrizione { get; set; }
        public string Descrizione_eng { get; set; }
        public Nullable<int> id_sottocategoria { get; set; }
    }
}
