//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;

    public partial class Sottocategorie
    {
        public int id_sottocategoria { get; set; }
        public string Nome { get; set; }
        public string Nome_eng { get; set; }
        public Nullable<double> Costo_Spedizione { get; set; }

        public List<Tipi_Immagini> listaTipi_Immagini { get; set; }

        public int? id_sottocategoria2
        {
            get
            {
                return id_sottocategoria;
            }
        }
    }
}
