//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabellaOrdiniTavolo
    {
        public int id { get; set; }
        public int id_tavolo { get; set; }
        public Nullable<int> id_prodotto { get; set; }
        public int id_gestione { get; set; }
        public string NomeProdotto { get; set; }
        public Nullable<int> id_categoria { get; set; }
        public Nullable<double> iva { get; set; }
        public Nullable<double> prezzoUnitario { get; set; }
        public string Ingredienti { get; set; }
        public string NoteTotali { get; set; }
        public Nullable<int> QuantitaTotale { get; set; }
        public Nullable<double> Sconto { get; set; }
    }
}
