//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestiHome
    {
        public int id_testo { get; set; }
        public Nullable<int> posizione { get; set; }
        public string testo_ita { get; set; }
        public string Testo_eng { get; set; }
        public string Titolo_eng { get; set; }
        public string Titolo_ita { get; set; }
    }
}
