//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipi_Immagini
    {
        public int id_tipo_immagine { get; set; }
        public string Descrizione_tipo_Immagine { get; set; }
        public bool Categoria { get; set; }
        public bool Prodotto { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Height { get; set; }
    }
}
