//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_DettaglioAlimentiProdotto
    {
        public int id_alimento_prodotto { get; set; }
        public int id_prodotto { get; set; }
        public int id_alimento { get; set; }
        public string Percentuale { get; set; }
        public string DescrizioneAlimento { get; set; }
        public string DescrizioneAlimento_eng { get; set; }
        public Nullable<bool> Allergeni { get; set; }
        public string ImgAlimento { get; set; }
        public string DescrizioneProdotto { get; set; }
        public string DescrizioneProdotto_eng { get; set; }
        public string ImgProdotto { get; set; }
        public string LottoAlimento { get; set; }
        public string LottoProdotto { get; set; }
        public Nullable<System.DateTime> DataProduzione { get; set; }
        public Nullable<System.DateTime> DataScadenza { get; set; }
        public bool Congelato { get; set; }
        public string BarCode { get; set; }
        public Nullable<double> iva { get; set; }
        public Nullable<double> PrezzoAcquisto { get; set; }
        public Nullable<double> PrezzoVendita { get; set; }
        public Nullable<int> Quantita { get; set; }
        public string Categoria { get; set; }
        public string Categoria_eng { get; set; }
        public string Marca { get; set; }
    }
}
